// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"bot/domain/article/scraper/infrastructure/repository"
	"bot/domain/article/scraper/usecase"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitScraper(storage *gorm.DB) usecase.Scraper {
	articleHub := repository.NewArticleHub(storage)
	article := repository.NewArticle(storage)
	scraper := usecase.NewScraper(articleHub, article)
	return scraper
}
