// Code generated by mockery v2.53.3. DO NOT EDIT.

package repository

import (
	entity "bot/domain/article/scraper/entity"

	mock "github.com/stretchr/testify/mock"
)

// MockArticleHub is an autogenerated mock type for the ArticleHub type
type MockArticleHub struct {
	mock.Mock
}

// Find provides a mock function with no fields
func (_m *MockArticleHub) Find() []entity.ArticleHub {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []entity.ArticleHub
	if rf, ok := ret.Get(0).(func() []entity.ArticleHub); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ArticleHub)
		}
	}

	return r0
}

// NewMockArticleHub creates a new instance of MockArticleHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticleHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticleHub {
	mock := &MockArticleHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
