version: 2.1

parameters:
  migration_branch: 
    type: string
    default: init


jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    environment:
      ssh: j3ns_devops
      working_dir: w8s-migration
      git: git@github.com:workshop-80s/migration.git
      branch: << pipeline.parameters.branch >>
    steps:
      - checkout
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "clone migration"
          command: | 
            git clone $git $working_dir
            cd $working_dir
            git checkout $branch
            git pull origin $branch
      

  test:  
    docker:
      - image: cimg/base:2023.03
    steps:
      - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
      - test:
          requires:
            - build

