version: 2.1

jobs:
  build: # this can be any name you choose  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "build hello world"
      
      - run: 
          name: "env"
          command: git clone git@github.com:workshop-80s/migration.git
      - run: 
          name: "env"
          command: ls -la
      - run: 
          name: "env"
          command: npm i
  # test:  
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout              
  #     - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
      # - test
