version: 2.1

parameters:
  migration_branch: 
    type: string
    default: main
  ssh: 
    type: string
    default: j3ns_devops


jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    environment:
      branch: << pipeline.parameters.migration_branch >>
      ssh: << pipeline.parameters.ssh >>
      working_dir: w8s-migration
      git: git@github.com:workshop-80s/migration.git
    steps:
      - checkout
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "clone migration"
          command: | 
            git clone $git $working_dir
            cd $working_dir
            git checkout $branch
            git pull origin $branch
      

  # test:  
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout              
  #     - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
            - migration_branch: init
      # - test:
      #     requires:
      #       - build

