version: 2.1


jobs:
  build: # this can be any name you choose
    steps:
      - checkout # checkout source code
      - run:
          name: debug
          command: echo $SSH_PRIVATE_KEY
workflows:
  initiate:
    jobs:
      - build