# https://circleci.com/docs/configuration-reference/
# https://circleci.com/docs/reusing-config/#parameter-syntax

version: 2.1

migration_branch: &migration_branch init

parameters:
  mysql_version:
    default: "8.0"
    type: string
  go_version:
    default: "1.23"
    type: string
  ssh: 
    type: string
    default: j3ns_devops
  migration_branch:
    default: *migration_branch
    type: string

executors:
  minimum:
    docker:
      - image: cimg/go:1.23
  main:
    docker:
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: buzz_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

jobs:
  setup_github:
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
    environment:
      ssh: << pipeline.parameters.ssh >>
    steps:
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - persist_to_workspace:
          # root: ~
          paths:
            - '.ssh'

  build:
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: buzz_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      migration_branch: << pipeline.parameters.migration_branch >>
      migration_dir: w8s-migration
      migration_git: git@github.com:workshop-80s/migration.git
    steps:
      - attach_workspace:
          at: ~
      - run:
          name: ssh
          command: |
            ls -la ~
            ls -la ~/.ssh
      # - run:
      #     name: mysql tool
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install -y default-mysql-client
      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      # - run:
      #     name: setup github
      #     command: |
      #       mkdir -p ~/.ssh 
      #       echo "$$ssh" > ~/.ssh/id_rsa
            
      #       chmod 600 ~/.ssh/id_rsa
      #       ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "clone migration (branch: << pipeline.parameters.migration_branch >>)"
          command: | 
            git clone $migration_git $migration_dir
            cd $migration_dir
            git checkout $migration_branch
            git pull origin $migration_branch
            go mod tidy
      - run: 
          name: "run migration"
          command: |
            cd $migration_dir
            ls -la
            go run main.go migration --env test up

  test:  
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "test hello world"

workflows:
  test:
    jobs:
      - setup_github
      - build:
          context:
            - github
          requires:
            - setup_github
      # - test:
      #     requires:
      #       - build

