# https://circleci.com/docs/configuration-reference/
# https://circleci.com/docs/reusing-config/#parameter-syntax

version: 2.1

migration_branch: &migration_branch init

parameters:
  mysql_version:
    default: "8.0"
    type: string
  go_version:
    default: "1.23"
    type: string
  ssh: 
    type: string
    default: j3ns_devops
  migration_branch:
    default: *migration_branch
    type: string


executors:
  main:
    working_directory: ~/project
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
      - image: circleci/mysql:8
        environment:
          MYSQL_DATABASE: buzz_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        command: |
          mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
jobs:
  build:
    executor: main
    environment:
      ssh: << pipeline.parameters.ssh >>
      migration_branch: << pipeline.parameters.migration_branch >>
      migration_dir: w8s-migration
      migration_git: git@github.com:workshop-80s/migration.git
    steps:
      - run:
          name: Wait for the database to start
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      # - run:
      #     name: mysql tool
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install -y default-mysql-client
      #       mysql -u root -h localhost buzz_test -e "SELECT 1;"
      #       # mysql -h $MYSQL_HOST -u $MYSQL_USER -p"$MYSQL_PASSWORD" $MYSQL_DATABASE -e "SELECT 1;"
      #       # Add your test commands here
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "clone migration (branch: << pipeline.parameters.migration_branch >>)"
          command: | 
            git clone $migration_git $migration_dir
            cd $migration_dir
            git checkout $migration_branch
            git pull origin $migration_branch
            go mod tidy
      - run: 
          name: "run migration"
          command: |
            cd $migration_dir
            ls -la
            go run main.go migration up

  test:  
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build
      # - dependency:
      #     context:
      #       - github
          # requires:
          #   - build
      # - test:
      #     requires:
      #       - build

