version: 2.1

jobs:
  test:
    docker:
      - image: circleci/golang:1.21
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: 3306
          MYSQL_DATABASE: testdb
          MYSQL_USER: root
          MYSQL_PASSWORD: password
      - image: mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
    working_directory: /go/src/github.com/yourusername/yourproject
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run: |
          # Wait for MySQL to be ready
          for i in `seq 1 10`;
          do
            nc -z 127.0.0.1 3306 && echo "MySQL is ready" && break
            echo "Waiting for MySQL..."
            sleep 5
          done
      - run: go test -v ./...

workflows:
  version: 2
  test:
    jobs:
      - test