version: 2.1

jobs:
  build: # this can be any name you choose  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "build hello world"
      - run: 
          name: log
          command: echo "log..."
      - run: 
        name: "env"
        command: echo "${SSH_PRIVATE_KEY}"
  # test:  
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout              
  #     - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
      # - test
