# https://circleci.com/docs/configuration-reference/
# https://circleci.com/docs/reusing-config/#parameter-syntax

version: 2.1

migration_branch: &migration_branch init

parameters:
  mysql_version:
    default: "8.0"
    type: string
  go_version:
    default: "1.23"
    type: string
  ssh: 
    type: string
    default: j3ns_devops
  migration_branch:
    default: *migration_branch
    type: string

jobs:
  build:
    docker:
      # - image: cimg/go:<< pipeline.parameters.go_version >>
      - image: cimg/base:2021.04
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: buzz_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
    steps:
      - run:
          name: Wait for MySQL to ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo "MySQL is ready" && break
              echo "Waiting for MySQL..."
              sleep 5
            done
      - run:
          name: mysql tool
          command: |
            sudo apt-get install mysql-client

  dependency:
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
    environment:
      ssh: << pipeline.parameters.ssh >>
      migration_branch: << pipeline.parameters.migration_branch >>
      migration_dir: w8s-migration
      migration_git: git@github.com:workshop-80s/migration.git
    steps:
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "clone migration (branch: << pipeline.parameters.migration_branch >>)"
          command: | 
            git clone $migration_git $migration_dir
            cd $migration_dir
            git checkout $migration_branch
            git pull origin $migration_branch
            go mod download
      # - run: 
      #     name: "run migration"
      #     command: |
      #       cd $migration_dir
      #       ls -la
      #       go run main.go migration up
  build2:
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - go-mod-{{ checksum "go.sum" }}
      # - run:
      #     name: Download Dependencies
      #     command: go mod download
      # - save_cache:
      #     key: go-mod-v1-{{ checksum "go.sum" }}
      #     paths:
      #       - /go/pkg/mod  # Default location for Go modules
      # - run:
      #     name: Build Application
      #     command: go build -v ./...
  
  test:  
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build
      - dependency:
          context:
            - github
          requires:
            - build
      - test:
          requires:
            - build

