version: 2.1

jobs:
  build: # this can be any name you choose  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Setup github
          command: |
            mkdir -p ~/.ssh
            echo "$ssh_key" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      # - run:
      #     name: Setup github
      #     command: |
      #       mkdir -p ~/.ssh
      #       echo "$ssh_key" > ~/.ssh/id_rsa
      #       chmod 600 ~/.ssh/id_rsa
      #       ssh-keyscan github.com >> ~/.ssh/known_hosts
      #       echo "$run_ssh" > ~/.ssh/deploy_rsa
      #       chmod 600 ~/.ssh/id_rsa
            # ssh-keyscan github.com >> ~/.ssh/known_hosts
      # - run: 
      #     name: "list dir"
      #     command: ls -la
      # - run: 
      #     name: "clone migration"
      #     command: | 
      #       git clone git@github.com:workshop-80s/migration.git w8s-migration
      #       cd w8s-migration
      #       git checkout init
      #       git pull origin init
  # test:  
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout              
  #     - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
      # - test
