version: 2.1

jobs:
  build: # this can be any name you choose  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "build hello world"
  # test:  
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout              
  #     - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build
      # - test
