# https://circleci.com/docs/configuration-reference/
# https://circleci.com/docs/reusing-config/#parameter-syntax

version: 2.1

migration_branch: &migration_branch init

parameters:
  ssh: 
    type: string
    default: j3ns_devops
  migration_branch:
    default: *migration_branch
    type: string

# executors:
#   minimum:
#     docker:
#       - image: cimg/go:1.23
#   main:
#     docker:
#       - image: cimg/mysql:8.0
#         environment:
#           MYSQL_DATABASE: buzz_test
#           MYSQL_ALLOW_EMPTY_PASSWORD: yes
#         command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

jobs:
  setup:
    working_directory: ~/project
    docker:
      - image: cimg/go:1.23
    environment:
      ssh: << pipeline.parameters.ssh >>
      migration_branch: << pipeline.parameters.migration_branch >>
      migration_dir: w8s-migration
      migration_git: git@github.com:workshop-80s/migration.git
    steps:
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "migration (branch: << pipeline.parameters.migration_branch >>)"
          command: | 
            git clone $migration_git $migration_dir
            cd $migration_dir
            git checkout $migration_branch
            git pull origin $migration_branch
            go mod tidy
      - run: 
          name: "ls"
          command: |
            pwd
            ls -la
      - persist_to_workspace:
          root: "."
          paths:
            - "*"

  build:
    working_directory: /main

    docker:
      - image: cimg/go:1.23
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: buzz_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    steps:
      - checkout
      # - run:
      #     name: mysql tool
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install -y default-mysql-client
      - attach_workspace:
          at: ~/project/w8s-migration
      - run: 
          name: "xxxxxxxxxxxx"
          command: |
            pwd
            ls -la
      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://localhost:3306 -timeout 1m

      - run: 
          name: "run migration"
          command: |
            cd $migration_dir
            ls -la
            go run main.go migration --env test up

workflows:
  build_test:
    jobs:
      - setup:
          context:
            - github
      - build:
          requires:
            - setup

