version: 2.1

jobs:
  build: # this can be any name you choose
    steps:
      - checkout              
      - run: echo "build hello world"
  test:
    steps:
      - checkout              
      - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build
      - test
