# https://circleci.com/docs/configuration-reference/
# https://circleci.com/docs/reusing-config/#parameter-syntax

version: 2.1

migration_branch: &migration_branch init

parameters:
  migration_branch:
    default: *migration_branch
    type: string
  go_version:
    default: "1.23"
    type: string
  ssh: 
    type: string
    default: j3ns_devops

jobs:
  build:
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
    environment:
      branch: *migration_branch
      ssh: << pipeline.parameters.ssh >>
      working_dir: w8s-migration
      git: git@github.com:workshop-80s/migration.git
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - go-mod-{{ checksum "go.sum" }}
      # - run:
      #     name: Download Dependencies
      #     command: go mod download
      # - save_cache:
      #     key: go-mod-v1-{{ checksum "go.sum" }}
      #     paths:
      #       - /go/pkg/mod  # Default location for Go modules
      # - run:
      #     name: Build Application
      #     command: go build -v ./...
  dependency:
    docker:
      - image: cimg/go:<< pipeline.parameters.go_version >>
    environment:
      migration_branch: *migration_branch
      ssh: << pipeline.parameters.ssh >>
      migration_dir: w8s-migration
      migration_git: git@github.com:workshop-80s/migration.git
    steps:
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "clone migration $($migration_branch) (<< pipeline.parameters.migration_branch >>)"
          command: | 
            git clone $migration_git $migration_dir
            cd $migration_dir
            git checkout $migration_branch
            git pull origin $migration_branch
            git branch
      # - run: 
      #     name: "build migration"
      #     command: go mod download
  test:  
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
      - dependency:
          requires:
            - build
      - test:
          requires:
            - dependency

