# https://circleci.com/docs/configuration-reference/
# https://circleci.com/docs/reusing-config/#parameter-syntax

version: 2.1

parameters:
  migration_branch:
    default: init
    type: string
  ssh: 
    type: string
    default: j3ns_devops

jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    environment:
      branch: << pipeline.parameters.migration_branch >>
      ssh: << pipeline.parameters.ssh >>
      working_dir: w8s-migration
      git: git@github.com:workshop-80s/migration.git
    steps:
      - checkout
  dependency:
    docker:
      - image: cimg/base:2023.03
    environment:
      ssh: << pipeline.parameters.ssh >>
      migration_branch: << pipeline.parameters.migration_branch >>
      migration_dir: w8s-migration
      migration_git: git@github.com:workshop-80s/migration.git
    steps:
      - run:
          name: setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$$ssh" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: 
          name: "clone migration"
          command: | 
            git clone $migration_git $migration_dir
            cd $migration_dir
            git checkout $migration_branch
            git pull origin $migration_branch
  test:  
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout              
      - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
      - dependency:
          requires:
            build
      - test:
          requires:
            - dependency

