version: 2.1

parameters:
    working_dir: 
      type: string
      default: "w8s-migration"
    git:
      type: string
      default: git@github.com:workshop-80s/migration.git
    branch: 
      type: string
      default: init
    sha1: 
      type: string
      default: init


jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run:
          name: Setup github
          command: |
            mkdir -p ~/.ssh 
            echo "$j3ns_devops" > ~/.ssh/id_rsa
            
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
          
  migration:
    docker:
      - image: cimg/base:2023.03
    environment:
      working_dir: << pipeline.parameters.working_dir >>
      git: << pipeline.parameters.git >>
      branch: << pipeline.parameters.branch >>
    steps:
      - run: 
          name: "clone migration"
          command: | 
            git clone $git $working_dir
            cd $working_dir
            git checkout $branch
            git pull origin $branch

  # test:  
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout              
  #     - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
      - migration:
          require:
            - build

