version: 2.1

variable:
  - &cmd "echo Hello World"
  - &migration_name "w8s-migration"

# name: &migration_name "w8s-migration"
# branch: &migration_branch init
# git:  &migration_git git@github.com:workshop-80s/migration.git


jobs:
  build: # this can be any name you choose  build:             echo "${{ variable.ssh_key }}" > ~/.ssh/id_rsa

    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: 
          name: "list dir"
          command: echo *migration_name
      # - run:
      #     name: Setup github
      #     command: |
      #       mkdir -p ~/.ssh 
      #       echo "$j3ns_devops" > ~/.ssh/id_rsa
            
      #       chmod 600 ~/.ssh/id_rsa
      #       ssh-keyscan github.com >> ~/.ssh/known_hosts
      # - run: 
      #     name: "list dir"
      #     command: ls -la
      - run: 
          name: "clone migration"
          command: | 
            git clone git@github.com:workshop-80s/migration.git *migration_name
            cd ./*migration_name
            git checkout *migration_branch
            git pull origin *migration_branch
  # test:  
  #   docker:
  #     - image: cimg/base:2023.03
  #   steps:
  #     - checkout              
  #     - run: echo "test hello world"

workflows:
  initiate:
    jobs:
      - build:
          context:
            - github
          
      # - test
