// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handler

import (
	"bot/domain/data_warehouse/article/infrastructure/repository"
	"bot/domain/data_warehouse/article/usecase"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitScraper(storage *gorm.DB) usecase.LinkScraper {
	hub := repository.NewHub(storage)
	link := repository.NewLink(storage)
	linkScraper := usecase.NewLinkScraper(hub, link)
	return linkScraper
}
