// Code generated by mockery v2.53.3. DO NOT EDIT.

package repository

import (
	mock "github.com/stretchr/testify/mock"

	entity "bot/domain/notify/entity"
)

// MockArticle is an autogenerated mock type for the Article type
type MockArticle struct {
	mock.Mock
}

// Find provides a mock function with no fields
func (_m *MockArticle) Find() []entity.Article {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []entity.Article
	if rf, ok := ret.Get(0).(func() []entity.Article); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Article)
		}
	}

	return r0
}

// NewMockArticle creates a new instance of MockArticle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArticle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArticle {
	mock := &MockArticle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
