// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package subscribe

import (
	"bot/domain/subscribe/infrastructure/repository"
	"bot/usecase/subscribe"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitialFlush(storage *gorm.DB) subscribe.Flush {
	article := repository.NewArticle(storage)
	flush := subscribe.NewFlush(article)
	return flush
}
